const SEARCH_NOTIFICATION = "SEARCH_NOTIFICATION";
const CHANGE_NOTIFICATION_STATUS = "CHANGE_NOTIFICATION_STATUS";
const status = {
  ARCHIVED: "archived",
  READ: "read",
  NEW: "new",
};
export { SEARCH_NOTIFICATION, CHANGE_NOTIFICATION_STATUS, status };
